### ISSUE TITLE
Upon opening, display the report for the location last entered

### ISSUE THREAD

**Issue by ndls60** [joshlsastro/weather#10]
As a user, I would like the app to open to the **_last_** location I viewed

**Comment by joshlsastro** [comment]
Will complete after #14 in case user wants to turn this off.

**Comment by ndls60** [comment]
How do I test it.  I tried opening it.  Selecting a location and viewing the forecast, then closing.  When I brought it up again, it landed on the main page.

**Comment by joshlsastro** [comment]
@ndls60 You need to enable it manually in settings; I didn't make it the default to avoid confusing users.
