### ISSUE TITLE
Aesthetic only: Move text to the right one page

### ISSUE THREAD

**Issue by ndls60** [joshlsastro/weather#12]
Text that begins on the left hand side of the main page is awkwardly too close to the left edge.  Add a space character as a prefix to all left handed text that start at the very left edge of the page.  Text on the forecast page don't have this issue because there is space between the enclosing box and the text.

**Comment by joshlsastro** [comment]
This does nothing to the paragraph. Some preliminary testing with CSS showed that, according to Firefox's development tools, this would render the site inaccessible on small mobile devices.
