### ISSUE TITLE
More Readable Current Weather Report

### ISSUE THREAD

**Issue by ndls60** [joshlsastro/weather#6]
I have a difficult time scanning the written observation report.  I think it would be easier to read if the data was more tabular and reorder the stats so I don't have to troll through half the report to get the temperature.  maybe something like this:

**Current Weather Observations
Temp:          32°F (null°C)
Wind:           SE 9 MPH (15 KPH)
Humidity:     0%**
**[Source](url)**:        Denver - Centennial Airport
Dew Point:   52°F (11.1°C)
Updated:     Tue Aug 06 2024 18:53:00 MDT
Conditions:  Mostly Cloudy
Pressure:     1023.4 mbar

**Comment by joshlsastro** [comment]
An actual HTML table ends up being less accessible on mobile. Reordering the stats will absolutely work, though.
